import React, { Component, useState } from "react";
import Styles from "./OceanSunset.css";
import Block from "./Block/Block";
import Sun from "./Sun/Sun";
import Stars from './Stars/Stars';

export default function OceanSunset()  {

   
    // Matrix of color blocks including: 
    //   color, 
    //   duration of linear gradient animation
    //   width of block
    //   height of block  

    const moon = [
      [{"color": "#1A222F", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#1E2633", "duration": "10", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#1F2935", "duration": "15", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#232C3B", "duration": "20", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#24303E", "duration": "13", "width": "100vw", "height": "6vh", "horizon": true }],
      [{"color": "#27333F", "duration": "19", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#2C363F", "duration": "19", "width": "100vw", "height": "9vh", "horizon": true }],
      [{"color": "#29323B", "duration": "14", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#272B36", "duration": "17", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#1F222C", "duration": "17", "width": "100vw", "height": "2vh", "horizon": false }],
      [{"color": "#262A33", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#242B35", "duration": "5", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#252934", "duration": "4", "width": "35vw", "height": "3vh", "horizon": false },
        {"color": "#2A2B34", "duration": "3", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#1E2730", "duration": "2", "width": "10vw", "height": "3vh", "horizon": false },
      ],
      // Moon width 8
      [{"color": "#252C36", "duration": "5", "width": "20vw", "height": "2vh", "horizon": false },
        {"color": "#222933", "duration": "4", "width": "26vw", "height": "2vh", "horizon": false },
        {"color": "#737D8C", "duration": "2", "width": "8vw", "height": "2vh", "horizon": false },
        {"color": "#22262F", "duration": "3", "width": "15vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "6", "width": "31vw", "height": "2vh", "horizon": false },
      ],
      // Moon width 10
      [{"color": "#242B35", "duration": "7", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#222933", "duration": "5", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "5", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#222631", "duration": "5", "width": "25vw", "height": "3vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "23vw", "height": "2vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "24vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "13vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "34vw", "height": "2vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "35vw", "height": "3vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "34vw", "height": "3vh", "horizon": false },
      ],     
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "25vw", "height": "2vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "19vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "30vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "14vw", "height": "2vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "39vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "24vw", "height": "3vh", "horizon": false },
      ],
      // Moon width 10
      [{"color": "#222A35", "duration": "2", "width": "40vw", "height": "4vh", "horizon": false },
        {"color": "#212934", "duration": "4", "width": "5vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "1vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "4vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "2vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#202833", "duration": "5", "width": "33vw", "height": "4vh", "horizon": false },
        {"color": "#1F2531", "duration": "5", "width": "12vw", "height": "4vh", "horizon": false },
      ],
      // Moon width 7
      [{"color": "#1F2732", "duration": "4", "width": "27vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "20vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "17vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "30vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#1F2732", "duration": "4", "width": "23vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "24vw", "height": "3vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "37vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#1F2732", "duration": "2", "width": "28vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "21vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "18vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "33vw", "height": "2vh", "horizon": false },
      ],
      
    ]

    const moonset = [
      [{"color": "#1A222F", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#1E2633", "duration": "10", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#1F2935", "duration": "15", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#232C3B", "duration": "20", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#24303E", "duration": "13", "width": "100vw", "height": "6vh", "horizon": true }],
      [{"color": "#27333F", "duration": "19", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#2C363F", "duration": "19", "width": "100vw", "height": "9vh", "horizon": true }],
      [{"color": "#29323B", "duration": "14", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#272B36", "duration": "17", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#1F222C", "duration": "17", "width": "100vw", "height": "2vh", "horizon": false }],
      [{"color": "#242B35", "duration": "5", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#252934", "duration": "4", "width": "35vw", "height": "3vh", "horizon": false },
        {"color": "#2A2B34", "duration": "3", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#1E2730", "duration": "2", "width": "10vw", "height": "3vh", "horizon": false },
      ],
      // Moon width 8
      [{"color": "#252C36", "duration": "5", "width": "20vw", "height": "2vh", "horizon": false },
        {"color": "#222933", "duration": "4", "width": "26vw", "height": "2vh", "horizon": false },
        {"color": "#737D8C", "duration": "2", "width": "8vw", "height": "2vh", "horizon": false },
        {"color": "#22262F", "duration": "3", "width": "15vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "6", "width": "31vw", "height": "2vh", "horizon": false },
      ],
      // Moon width 10
      [{"color": "#242B35", "duration": "7", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#222933", "duration": "5", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#9097A0", "duration": "4", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "5", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#222631", "duration": "5", "width": "25vw", "height": "3vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "23vw", "height": "2vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "24vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "13vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "34vw", "height": "2vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "35vw", "height": "3vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "34vw", "height": "3vh", "horizon": false },
      ],     
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "25vw", "height": "2vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "19vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "30vw", "height": "2vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "14vw", "height": "2vh", "horizon": false },
      ],
      // Moon reflection width 12
      [{"color": "#232A34", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#242833", "duration": "5", "width": "39vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "1vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#202731", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#212530", "duration": "2", "width": "24vw", "height": "3vh", "horizon": false },
      ],
      // Moon width 10
      [{"color": "#222A35", "duration": "2", "width": "40vw", "height": "4vh", "horizon": false },
        {"color": "#212934", "duration": "4", "width": "5vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "1vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "4vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "2vw", "height": "4vh", "horizon": false },
        {"color": "#A4A7AB", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#202833", "duration": "5", "width": "33vw", "height": "4vh", "horizon": false },
        {"color": "#1F2531", "duration": "5", "width": "12vw", "height": "4vh", "horizon": false },
      ],
      // Moon width 7
      [{"color": "#1F2732", "duration": "4", "width": "27vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "20vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "2vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "17vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "30vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#1F2732", "duration": "4", "width": "23vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "25vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".5vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1.5vw", "height": "2vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "11vw", "height": "2vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "37vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#1F2732", "duration": "4", "width": "23vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "25vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".3vw", "height": "1vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".5vw", "height": "1vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": ".5vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".3vw", "height": "1vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": ".5vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".2vw", "height": "1vh", "horizon": false },
        {"color": "#979CA3", "duration": "3", "width": "1vw", "height": "1vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": ".3vw", "height": "1vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "11vw", "height": "1vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "37vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#1F2732", "duration": "4", "width": "23vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "11vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "37vw", "height": "3vh", "horizon": false },
      ],      
      [{"color": "#1F2732", "duration": "4", "width": "13vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "2", "width": "35vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#1D2530", "duration": "3", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "6", "width": "2vw", "height": "3vh", "horizon": false },
        {"color": "#1E2631", "duration": "5", "width": "57vw", "height": "3vh", "horizon": false },
      ],

    ]

    const sunrise = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true}],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true}],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false}], // horizon
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false }
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const sun = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false}],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false}],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const midsunset = [
        [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
        [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
        [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
        [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
        [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
        [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
        [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
        [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
        [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
        [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
        [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
          {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
          {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
          {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
          {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
        ],
        [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
          {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
          {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
          {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
          {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
        ],
        [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
          {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
          {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
          {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
        ],
        [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
          {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
          {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
          {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
        ],
        [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
          {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
          {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
          {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
        ],
        [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
          {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
          {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
          {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
          {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
        ],
        [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
          {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
          {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
          {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
          {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
        ],
        [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
          {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
          {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
          {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
          {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
        ],
        [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
          {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
          {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
          {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
          {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
        ],
        [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
          {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
          {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
          {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
          {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
        ],
        
    ]

    // DONE
    const sunset = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const moonrise = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]


    const time = new Date().getHours();
    let timeOfDay = [];
    let sunStyle = "";
    let starBool = false;

    // The if/else statements
    if (time <= 4) {
      timeOfDay = moon;
      sunStyle = "moon";
      starBool= true;
    } else if (time >= 4 && time < 5) {
      timeOfDay = moonset;
      sunStyle = "moonset";
      starBool= true;
    } else if (time >= 6 && time < 12){
      timeOfDay = sunrise;
      sunStyle = "sunrise";
      starBool= false;
    } else if (time >= 12 && time < 16){
      timeOfDay = sun;
      sunStyle = "daysun";
      starBool= false;
    } else if (time >= 16 && time < 17){
      timeOfDay = midsunset;
      sunStyle = "midsunset";
      starBool= false;
    } else if (time >= 17 && time < 18){
      timeOfDay = sunset;
      sunStyle = "sunset";
      starBool= false;
    } else if (time >= 18 && time < 24){
      timeOfDay = moonrise;
      sunStyle = "moonrise";
      starBool= true;
    } else {
      timeOfDay = moon;
      sunStyle = "moon";
      starBool= true;
    }

    
    return (
      <div className="ocean-sunset-container">

        {starBool ? <Stars /> : null}
        {/* <Stars /> */}

        {/* Sun component */}
        <Sun sunStyle={sunStyle}/>
        
        {/* Outer loop to iterate through color matrix row-by-row */}
        {timeOfDay.map((items, index) => {
          
          return (
            <div key={index} className="row-container">
              {/* Inner loop to iterate through color matrix column-by-column */}
              {items.map((subItems, subIndex) => {

                return (
                  <Block  key={index + "-" + subIndex} blockNumber={index} blockSubNumber={subIndex} blockColor={subItems.color} blockSecondColor={subItems.color2} blockWidth={subItems.width} blockHeight={subItems.height} blockDuration={subItems.duration} horizon={subItems.horizon} numSubItems={items.length} />
                )
              })}
            </div>
          )
        })}
              
      </div>
    );
  
}