import React, { Component, useState } from "react";
import Styles from "./OceanSunset.css";
import Block from "./Block/Block";
import Sun from "./Sun/Sun";

export default function OceanSunset()  {

   
    // Matrix of color blocks including: 
    //   color, 
    //   duration of linear gradient animation
    //   width of block
    //   height of block  

    const moon = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const moonset = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const sunrise = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true}],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true}],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false}], // horizon
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false }
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const sun = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false}],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false}],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const midsunset = [
        [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
        [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
        [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
        [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
        [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
        [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
        [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
        [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
        [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
        [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
        [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
          {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
          {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
          {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
          {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
        ],
        [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
          {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
          {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
          {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
          {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
        ],
        [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
          {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
          {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
          {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
        ],
        [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
          {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
          {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
          {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
        ],
        [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
          {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
          {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
          {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
        ],
        [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
          {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
          {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
          {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
          {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
        ],
        [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
          {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
          {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
          {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
          {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
        ],
        [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
          {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
          {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
          {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
          {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
        ],
        [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
          {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
          {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
          {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
          {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
        ],
        [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
          {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
          {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
          {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
          {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
        ],
        
    ]

    // DONE
    const sunset = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]

    const moonrise = [
      [{"color": "#764F62", "duration": "12", "width": "100vw", "height": "2vh", "horizon": true }],
      [{"color": "#6E475A", "duration": "10", "width": "100vw", "height": "13vh", "horizon": true }],
      [{"color": "#6A4356", "duration": "15", "width": "100vw", "height": "8vh", "horizon": true }],
      [{"color": "#634456", "duration": "20", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#60445A", "duration": "13", "width": "100vw", "height": "10vh", "horizon": true }],
      [{"color": "#54475B", "duration": "19", "width": "100vw", "height": "4vh", "horizon": true }],
      [{"color": "#4D4D5F", "duration": "11", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#454E5D", "duration": "19", "width": "100vw", "height": "7vh", "horizon": true }],
      [{"color": "#70646A", "duration": "14", "width": "100vw", "height": "1vh", "horizon": false }],
      [{"color": "#866B6A", "duration": "17", "width": "100vw", "height": "4vh", "horizon": false }],
      [{"color": "#52504E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#4B5052", "duration": "4", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#2D3238", "duration": "3", "width": "5vw", "height": "3vh", "horizon": false },
        {"color": "#5C6D81", "duration": "2", "width": "20vw", "height": "3vh", "horizon": false },
        {"color": "#6E7D8E", "duration": "3", "width": "63vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#675D5C", "duration": "5", "width": "3vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "4", "width": "12vw", "height": "2vh", "horizon": false },
        {"color": "#43444B", "duration": "2", "width": "4vw", "height": "2vh", "horizon": false },
        {"color": "#465666", "duration": "3", "width": "35vw", "height": "2vh", "horizon": false },
        {"color": "#667486", "duration": "6", "width": "46vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#635959", "duration": "7", "width": "9vw", "height": "3vh", "horizon": false },
        {"color": "#59514F", "duration": "5", "width": "30vw", "height": "3vh", "horizon": false },
        {"color": "#465666", "duration": "4", "width": "25vw", "height": "3vh", "horizon": false },
        {"color": "#526373", "duration": "5", "width": "36vw", "height": "3vh", "horizon": false },
      ],
      [{"color": "#635353", "duration": "3", "width": "5vw", "height": "2vh", "horizon": false },
        {"color": "#505053", "duration": "5", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#2E3339", "duration": "6", "width": "7vw", "height": "2vh", "horizon": false },
        {"color": "#59514F", "duration": "2", "width": "81vw", "height": "2vh", "horizon": false },
      ],
      [{"color": "#5C5050", "duration": "2", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#77655E", "duration": "4", "width": "20vw", "height": "4vh", "horizon": false },
        {"color": "#836560", "duration": "3", "width": "55vw", "height": "4vh", "horizon": false },
        {"color": "#77605A", "duration": "5", "width": "32vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#64524E", "duration": "3", "width": "2vw", "height": "1vh", "horizon": false },
        {"color": "#342E2E", "duration": "5", "width": "5vw", "height": "1vh", "horizon": false },
        {"color": "#6D5D56", "duration": "2", "width": "20vw", "height": "1vh", "horizon": false },
        {"color": "#745356", "duration": "4", "width": "40vw", "height": "1vh", "horizon": false },
        {"color": "#575452", "duration": "7", "width": "40vw", "height": "1vh", "horizon": false },
      ],
      [{"color": "#232325", "duration": "5", "width": "1vw", "height": "7vh", "horizon": false },
        {"color": "#342E2E", "duration": "4", "width": "5vw", "height": "7vh", "horizon": false },
        {"color": "#1F2024", "duration": "6", "width": "15vw", "height": "7vh", "horizon": false },
        {"color": "#2D3134", "duration": "7", "width": "50vw", "height": "7vh", "horizon": false },
        {"color": "#48494D", "duration": "5", "width": "29vw", "height": "7vh", "horizon": false },
      ],
      [{"color": "#49433D", "duration": "3", "width": "3vw", "height": "4vh", "horizon": false },
        {"color": "#3F3B38", "duration": "7", "width": "8vw", "height": "4vh", "horizon": false },
        {"color": "#504645", "duration": "3", "width": "60vw", "height": "4vh", "horizon": false },
        {"color": "#645A57", "duration": "5", "width": "50vw", "height": "4vh", "horizon": false },
        {"color": "#564E4C", "duration": "6", "width": "29vw", "height": "4vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "4", "width": "3vw", "height": "5vh", "horizon": false },
        {"color": "#463637", "duration": "2", "width": "10vw", "height": "5vh", "horizon": false },
        {"color": "#463434", "duration": "3", "width": "15vw", "height": "5vh", "horizon": false },
        {"color": "#443135", "duration": "6", "width": "60vw", "height": "5vh", "horizon": false },
        {"color": "#706F79", "duration": "5", "width": "12vw", "height": "5vh", "horizon": false },
      ],
      [{"color": "#372D2E", "duration": "5", "width": "3vw", "height": "3vh", "horizon": false },
        {"color": "#463637", "duration": "4", "width": "10vw", "height": "3vh", "horizon": false },
        {"color": "#463434", "duration": "8", "width": "15vw", "height": "3vh", "horizon": false },
        {"color": "#443135", "duration": "7", "width": "70vw", "height": "3vh", "horizon": false },
        {"color": "#474143", "duration": "5", "width": "2vw", "height": "3vh", "horizon": false },
      ],
      
    ]


    const time = new Date().getHours();
    let timeOfDay = [""];
    let sunStyle = "";

    // The if/else statements
    if (time <= 4) {
      timeOfDay = moon;
      sunStyle = "moon";
    } else if (time >= 4 && time < 5) {
      timeOfDay = moonset;
      sunStyle = "moonset";
    } else if (time >= 6 && time < 12){
      timeOfDay = sunrise;
      sunStyle = "sunrise";
    } else if (time >= 12 && time < 16){
      timeOfDay = sun;
      sunStyle = "daysun";
    } else if (time >= 16 && time < 17){
      timeOfDay = midsunset;
      sunStyle = "midsunset";
    } else if (time >= 17 && time < 18){
      timeOfDay = sunset;
      sunStyle = "sunset";
    } else if (time >= 18 && time < 24){
      timeOfDay = moonrise;
      sunStyle = "moonrise";
    } else {
      timeOfDay = moon;
      sunStyle = "moon";
    }

    
    return (
      <div className="ocean-sunset-container">

        {/* Sun component */}
        <Sun sunStyle={"sunstyle"}/>
        
        {/* Outer loop to iterate through color matrix row-by-row */}
        {timeOfDay.map((items, index) => {
          
          return (
            <div key={index} className="row-container">
              {/* Inner loop to iterate through color matrix column-by-column */}
              {items.map((subItems, subIndex) => {

                return (
                  <Block  key={index + "-" + subIndex} blockNumber={index} blockSubNumber={subIndex} blockColor={subItems.color} blockSecondColor={subItems.color2} blockWidth={subItems.width} blockHeight={subItems.height} blockDuration={subItems.duration} horizon={subItems.horizon}/>
                )
              })}
            </div>
          )
        })}
              
      </div>
    );
  
}